export function buildOpenApiDocument() {
  return {
    openapi: "3.1.0",
    info: {
      title: "CCHistory Local API",
      version: "0.1.0",
    },
    paths: {
      "/health": { get: { summary: "Health check" } },
      "/api/sources": { get: { summary: "List sources" } },
      "/api/turns": { get: { summary: "List resolved turns" } },
      "/api/turns/search": { get: { summary: "Search turns" } },
      "/api/turns/{turnId}": { get: { summary: "Get turn detail" } },
      "/api/turns/{turnId}/context": { get: { summary: "Get turn context" } },
      "/api/sessions/{sessionId}": { get: { summary: "Get session detail" } },
      "/api/admin/sessions/{sessionId}/related-work": { get: { summary: "Get typed related-work relations for a session" } },
      "/api/projects": { get: { summary: "List committed projects" } },
      "/api/projects/{projectId}": { get: { summary: "Resolve a project id to the current project revision" } },
      "/api/projects/{projectId}/turns": { get: { summary: "List project turns" } },
      "/api/projects/{projectId}/revisions": { get: { summary: "List project revisions and lineage events" } },
      "/api/artifacts": {
        get: { summary: "List knowledge artifacts" },
        post: { summary: "Create or update a knowledge artifact" },
      },
      "/api/artifacts/{artifactId}/coverage": { get: { summary: "List artifact coverage rows" } },
      "/api/admin/linking": { get: { summary: "Get linking review queue" } },
      "/api/admin/linking/overrides": {
        get: { summary: "List manual linking overrides" },
        post: { summary: "Create or update a manual linking override" },
      },
      "/api/admin/projects/lineage-events": {
        post: { summary: "Append explicit split, merge, superseded, or override lineage events for a project" },
      },
      "/api/admin/projects/{projectId}/delete": {
        post: { summary: "Delete a project and purge its currently linked local data" },
      },
      "/api/admin/lifecycle/candidate-gc": { post: { summary: "Archive or purge candidate turns older than a cutoff" } },
      "/api/agent/pair": { post: { summary: "Pair a remote agent" } },
      "/api/agent/heartbeat": { post: { summary: "Record remote-agent liveness and source-manifest state" } },
      "/api/agent/jobs/lease": { post: { summary: "Lease one pending remote-agent collection job" } },
      "/api/agent/uploads": { post: { summary: "Upload one remote-agent bundle" } },
      "/api/agent/jobs/{jobId}/complete": { post: { summary: "Report remote-agent collection job completion or failure" } },
      "/api/admin/agents": { get: { summary: "List paired remote agents and their current inventory" } },
      "/api/admin/agent-jobs": {
        get: { summary: "List remote-agent collection jobs and per-agent status" },
        post: { summary: "Create a remote-agent collection job" },
      },
      "/api/admin/agents/{agentId}/labels": { post: { summary: "Update operator-facing remote-agent labels and display name" } },
      "/api/admin/source-config": {
        get: { summary: "List source configuration and current effective directories" },
        post: { summary: "Add a manual source instance for a supported source platform" },
      },
      "/api/admin/source-config/{sourceId}": { post: { summary: "Override the base directory for a configured source" } },
      "/api/admin/source-config/{sourceId}/reset": { post: { summary: "Reset a source base directory back to its default" } },
      "/api/admin/probe/sources": { get: { summary: "List probe source definitions" } },
      "/api/admin/probe/runs": { post: { summary: "Run a local probe" } },
      "/api/admin/pipeline/replay": { post: { summary: "Replay the pipeline without persistence" } },
      "/api/admin/pipeline/runs": { get: { summary: "List stage runs" } },
      "/api/admin/pipeline/blobs": { get: { summary: "List captured blobs" } },
      "/api/admin/pipeline/records": { get: { summary: "List raw records" } },
      "/api/admin/pipeline/fragments": { get: { summary: "List source fragments" } },
      "/api/admin/pipeline/atoms": { get: { summary: "List conversation atoms" } },
      "/api/admin/pipeline/edges": { get: { summary: "List atom edges" } },
      "/api/admin/pipeline/candidates": { get: { summary: "List derived candidates" } },
      "/api/admin/pipeline/loss-audits": { get: { summary: "List loss audits" } },
      "/api/admin/pipeline/lineage/{turnId}": { get: { summary: "Get turn lineage drill-down" } },
      "/api/admin/masks": { get: { summary: "List mask templates" } },
      "/api/admin/drift": { get: { summary: "Get drift diagnostics" } },
      "/api/tombstones/{logicalId}": { get: { summary: "Resolve a purged logical id to a tombstone projection" } },
    },
  };
}
