import {
  listCommandsForCompletion,
  listGlobalOptionNamesForCompletion,
  type CompletionCommandInfo,
} from "../args.js";
import type { CommandContext, CommandOutput } from "../main.js";
import { usageError } from "../errors.js";

const SUPPORTED_SHELLS = ["bash", "zsh", "fish"] as const;
type SupportedShell = (typeof SUPPORTED_SHELLS)[number];

interface CommandTree {
  topLevel: string[];
  /** parent path → direct children */
  children: Map<string, string[]>;
  /** full path (joined with space) → option names */
  optionsByPath: Map<string, string[]>;
}

export function handleCompletions(context: CommandContext): CommandOutput {
  const shellArg = context.positionals[0]?.trim().toLowerCase();
  if (!shellArg) {
    throw usageError(
      `Specify a target shell: ${SUPPORTED_SHELLS.join(", ")}. Example: eval "$(cchistory completions bash)"`,
    );
  }
  if (!SUPPORTED_SHELLS.includes(shellArg as SupportedShell)) {
    throw usageError(
      `Unsupported shell ${JSON.stringify(shellArg)}. Choose one of: ${SUPPORTED_SHELLS.join(", ")}.`,
    );
  }
  const globals = listGlobalOptionNamesForCompletion();
  const tree = buildCommandTree(listCommandsForCompletion(), globals);
  const shell = shellArg as SupportedShell;
  const script = shell === "bash"
    ? renderBash(tree)
    : shell === "zsh"
      ? renderZsh(tree)
      : renderFish(tree);
  return { text: script, json: { shell, script } };
}

function buildCommandTree(commands: CompletionCommandInfo[], globals: string[]): CommandTree {
  const topLevel = commands.filter((cmd) => cmd.path.length === 1).map((cmd) => cmd.path[0]!);
  const children = new Map<string, string[]>();
  const optionsByPath = new Map<string, string[]>();
  for (const cmd of commands) {
    const pathKey = cmd.path.join(" ");
    optionsByPath.set(pathKey, [...globals, ...cmd.options]);
    if (cmd.path.length >= 2) {
      for (let depth = 1; depth < cmd.path.length; depth += 1) {
        const parent = cmd.path.slice(0, depth).join(" ");
        const tail = cmd.path[depth]!;
        const list = children.get(parent) ?? [];
        if (!list.includes(tail)) list.push(tail);
        children.set(parent, list);
      }
    }
  }
  return { topLevel, children, optionsByPath };
}

// ── bash ──

function renderBash(tree: CommandTree): string {
  const lines: string[] = [
    "# cchistory bash completion — generated by `cchistory completions bash`.",
    '# Install: eval "$(cchistory completions bash)" (add to ~/.bashrc for persistence).',
    "",
    "_cchistory_complete() {",
    "  local cur prev words cword",
    "  _init_completion 2>/dev/null || {",
    "    cur=\"${COMP_WORDS[COMP_CWORD]}\"",
    "    prev=\"${COMP_WORDS[COMP_CWORD - 1]}\"",
    "    cword=$COMP_CWORD",
    "  }",
    "",
    "  # Skip the leading cchistory word; collect positionals until we hit a flag.",
    "  local path=()",
    "  local i=1",
    '  while [ $i -lt $COMP_CWORD ]; do',
    '    local w="${COMP_WORDS[$i]}"',
    '    if [[ "$w" == -* ]]; then break; fi',
    '    path+=("$w")',
    '    i=$((i+1))',
    "  done",
    "",
  ];

  lines.push(`  local TOP_CMDS="${tree.topLevel.join(" ")}"`);
  lines.push("");

  // No path yet → suggest top-level commands.
  lines.push("  # No subcommand picked yet: suggest top-level commands.");
  lines.push('  if [ ${#path[@]} -eq 0 ]; then');
  lines.push('    COMPREPLY=( $(compgen -W "$TOP_CMDS" -- "$cur") )');
  lines.push("    return 0");
  lines.push("  fi");
  lines.push("");

  // For each known parent path, suggest children OR options depending on
  // whether the user is still typing the next positional.
  //
  // IMPORTANT: case patterns with `|` alternation cannot be wrapped in a
  // single pair of double quotes — bash treats `"a|b"` as a literal string,
  // so the alternation never fires. But patterns containing spaces (which
  // arise for parents like "maintenance gc-evidence") cannot be left unquoted
  // either — bash tokenizes on the unquoted space and reports a syntax error.
  // We resolve both by quoting each alternation piece individually:
  //   "ls"|"ls sessions"|"ls sources")
  // Each piece is a literal match (no glob chars), and `|` between quoted
  // pieces is the alternation operator.
  lines.push("  local path_key=\"${path[*]}\"");
  lines.push("  local -a kids opts");
  lines.push("  case \"$path_key\" in");
  const handled = new Set<string>();
  for (const [parent, childList] of tree.children) {
    if (handled.has(parent)) continue;
    handled.add(parent);
    // Build alternation pieces: parent alone + each "parent child" pair.
    // Each piece is double-quoted so embedded spaces are preserved.
    const altPieces = [
      escapeBashCase(parent),
      ...childList.map((child) => `${escapeBashCase(parent)} ${escapeBashCase(child)}`),
    ];
    const pattern = altPieces.map((p) => `"${escapeBashDouble(p)}"`).join("|");
    // Match parent path exactly OR parent path + one of its children (so we
    // can switch from suggesting children to suggesting options).
    lines.push(`    ${pattern})`);
    lines.push(`      kids="${childList.map(escapeBashDouble).join(" ")}"`);
    // If the path so far equals just the parent, the user is still typing the
    // next positional — suggest children. Emitted on its own lines so `bash -n`
    // accepts the script (the prior one-line form ended with `return 0 fi`,
    // which is a syntax error).
    lines.push(`      if [ "\${path[*]}" = "${escapeBashDouble(parent)}" ]; then`);
    lines.push('        COMPREPLY=( $(compgen -W "$kids" -- "$cur") )');
    lines.push('        return 0');
    lines.push('      fi');
    lines.push("      ;;");
  }
  lines.push("  esac");
  lines.push("");

  // For the deepest matched path, suggest options. Each option name in the
  // spec is stored without the leading `--` (so fish/zsh can use `-l store`);
  // bash needs the `--` so compgen matches what the user typed. The case
  // pattern here is a single path (no `|`), so we can double-quote the whole
  // thing — that preserves any embedded spaces (e.g. "maintenance gc-evidence")
  // without disabling alternation (there is none to disable).
  lines.push("  # Fall through: suggest option flags for the matched path.");
  lines.push('  opts=""');
  lines.push("  case \"$path_key\" in");
  for (const [pathKey, opts] of tree.optionsByPath) {
    lines.push(`    "${escapeBashDouble(pathKey)}") opts="${opts.map((o) => "--" + escapeBashDouble(o)).join(" ")}" ;;`);
  }
  lines.push("  esac");
  lines.push('  COMPREPLY=( $(compgen -W "$opts" -- "$cur") )');
  lines.push("  return 0");
  lines.push("}");
  lines.push("complete -F _cchistory_complete cchistory");
  return lines.join("\n");
}

function escapeBashCase(s: string): string {
  // Spaces are preserved (case patterns treat them literally inside quotes);
  // we just need to escape the few characters that bash globbing cares about.
  return s.replace(/([[*?()])/g, "\\$1");
}

function escapeBashDouble(s: string): string {
  // Escape characters that are special inside bash double-quoted strings.
  return s.replace(/([\\$"`])/g, "\\$1");
}

// ── zsh ──

function renderZsh(tree: CommandTree): string {
  const lines: string[] = [
    "#compdef cchistory",
    "# cchistory zsh completion — generated by `cchistory completions zsh`.",
    '# Install: eval "$(cchistory completions zsh)" or save as _cchistory on $fpath.',
    "",
    "_cchistory() {",
    "  local -a top",
    "  top=(",
  ];
  for (const cmd of tree.topLevel) {
    lines.push(`    '${cmd}:${escapeZsh(cmd + " command")}'`);
  }
  lines.push("  )");
  lines.push("");
  lines.push("  _arguments -C \\");
  lines.push('    "1: :->topcmd" \\');
  lines.push('    "*::arg:->args"');
  lines.push("");
  lines.push("  case $state in");
  lines.push("    topcmd) _describe 'cchistory command' top ;;");
  lines.push("    args)");
  lines.push("      case $line[1] in");
  for (const topCmd of tree.topLevel) {
    const childList = tree.children.get(topCmd) ?? [];
    const opts = tree.optionsByPath.get(topCmd) ?? [];
    lines.push(`        ${topCmd})`);
    if (childList.length > 0) {
      lines.push("          local -a subs");
      lines.push("          subs=(");
      for (const sub of childList) {
        lines.push(`            '${sub}:${escapeZsh(sub + " subcommand")}'`);
      }
      lines.push("          )");
      lines.push("          _arguments -C \\");
      lines.push('            "1: :->subcmd" \\');
      lines.push('            "*::arg:->subargs"');
      lines.push("          case $state in");
      lines.push("            subcmd) _describe 'subcommand' subs ;;");
      lines.push("            subargs)");
      lines.push("              local -a opts");
      lines.push("              case $line[1] in");
      for (const sub of childList) {
        const subOpts = tree.optionsByPath.get(`${topCmd} ${sub}`) ?? [];
        lines.push(`                ${sub}) opts=(${subOpts.map((o) => `'--${o}'`).join(" ")}) ;;`);
      }
      lines.push("              esac");
      lines.push("              _values 'options' $opts ;;");
      lines.push("          esac");
    } else {
      lines.push(`          _values 'options' ${opts.map((o) => `'--${o}'`).join(" ")}`);
    }
    lines.push("          ;;");
  }
  lines.push("      esac");
  lines.push("      ;;");
  lines.push("  esac");
  lines.push("}");
  lines.push("");
  lines.push("_cchistory \"$@\"");
  return lines.join("\n");
}

function escapeZsh(s: string): string {
  // Inside single quotes, the only special sequence is ''. We escape ' as ''.
  return s.replace(/'/g, "''");
}

// ── fish ──

function renderFish(tree: CommandTree): string {
  const lines: string[] = [
    "# cchistory fish completion — generated by `cchistory completions fish`.",
    "# Install: cchistory completions fish > ~/.config/fish/completions/cchistory.fish",
    "",
    "# Top-level commands.",
    `complete -c cchistory -n "__fish_use_subcommand" -a "${tree.topLevel.join(" ")}"`,
    "",
    "# Subcommands (chained conditions match the full parent path).",
  ];

  for (const [parent, childList] of tree.children) {
    const condition = fishConditionForParent(parent);
    lines.push(
      `complete -c cchistory -n "${condition}" -a "${childList.join(" ")}"`,
    );
  }

  lines.push("");
  lines.push("# Option flags per active command path.");
  for (const [pathKey, opts] of tree.optionsByPath) {
    if (opts.length === 0) continue;
    const condition = fishConditionForExactPath(pathKey);
    for (const opt of opts) {
      lines.push(
        `complete -c cchistory -n "${condition}" -l ${opt}`,
      );
    }
  }
  return lines.join("\n");
}

function fishConditionForParent(parent: string): string {
  const parts = parent.split(" ");
  if (parts.length === 0) return "__fish_use_subcommand";
  // __fish_seen_subcommand_from returns true if any of the named subcommands
  // has been seen. To require an exact chain, we combine multiple calls with
  // "; and " — fish evaluates them in sequence against the same command line.
  const conditions = parts.map((_, index) => {
    const chain = parts.slice(0, index + 1);
    return `__fish_seen_subcommand_from ${chain.join(" ")}`;
  });
  // The strongest condition is the deepest chain; weaker conditions would
  // also match so we keep only the deepest.
  return conditions[conditions.length - 1] ?? "__fish_use_subcommand";
}

function fishConditionForExactPath(pathKey: string): string {
  // For options, we want the parent path to be exactly the command path
  // (i.e. the user has finished typing the subcommand chain).
  const parts = pathKey.split(" ");
  if (parts.length === 1) {
    return `__fish_seen_subcommand_from ${parts[0]}`;
  }
  // Chain all parts; the last call ensures we are positioned inside the
  // deepest subcommand context.
  return parts.map((_, index) => {
    const chain = parts.slice(0, index + 1);
    return `__fish_seen_subcommand_from ${chain.join(" ")}`;
  }).join("; and ");
}
